---
title: "Vaccination Registration"
output: html_notebook # html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("maps")
install.packages("ggplot2")
install.packages("ggthemes")
install.packages("scales")
install.packages("plyr")
install.packages("dplyr")
install.packages("scales")
install.packages("stringr")
```

```{r}
library(maps)
library(ggplot2)
library(ggthemes)
library(plyr)
library(dplyr)
library(scales)
library(stringr)
```

```{r}

reg_MY_url <- "E:/Programming/R/stats-assignment/dataset/citf-public-main/registration/vaxreg_malaysia.csv"

reg_state_url <- "E:/Programming/R/stats-assignment/dataset/citf-public-main/registration/vaxreg_state.csv"

pop_url <- "E:/Programming/R/stats-assignment/dataset/covid19-public-main/static/population.csv"

reg_MY <- read.csv(reg_MY_url)
reg_state <- read.csv(reg_state_url)
population <- read.csv(pop_url)
```

```{r}
ggplot(reg_MY, aes(x = as.Date(date), y = total )) + geom_line() + scale_y_continuous(expand = c(0,0), breaks = pretty_breaks(), labels = comma) + scale_x_date(date_breaks = "1 month", labels = date_format("%d-%b"))

ggplot(reg_MY, aes(x = as.Date(date), y = total )) + geom_line() + scale_y_continuous(breaks = pretty_breaks(), labels = comma) + scale_x_date(date_breaks = "1 month", labels = date_format("%d-%b"))
```

```{r}
ggplot(reg_MY, aes(x = as.Date(date), y = children )) + geom_line() + scale_y_continuous(breaks = pretty_breaks(), labels = comma) + scale_x_date(date_breaks = "1 month", labels = date_format("%d-%b"))

```

```{r}
adult <- reg_MY$total - reg_MY$elderly - reg_MY$children

ggplot(reg_MY, aes(as.Date(date))) + geom_line(aes(y = total, color = "Total")) + geom_line(aes(y = children, color = "Children")) + geom_line(aes(y = adult, color = "Adult")) + geom_line(aes(y = elderly, color = "Elderly")) + scale_y_continuous(breaks = pretty_breaks(), labels = comma) + scale_x_date(date_breaks = "1 month", labels = date_format("%d-%b")) + labs(x = "Date", y = "Total Registration", title = "Cumulative Total Registration For Vaccination in Malaysia", color = "Age Class")

ggplot(reg_MY, aes(as.Date(date))) + geom_line(aes(y = total, color = "Total")) + geom_line(aes(y = children, color = "Below 18")) + geom_line(aes(y = adult, color = "18-59")) + geom_line(aes(y = elderly, color = "60 and above")) + scale_y_continuous(breaks = pretty_breaks(), labels = comma) + scale_x_date(date_breaks = "1 month", labels = date_format("%d-%b")) + labs(x = "Date", y = "Total Registration", title = "Cumulative Total Registration For Vaccination in Malaysia", color = "Age Class")

ggplot(reg_MY, aes(as.Date(date))) + geom_line(aes(y = total, color = "Total")) + geom_line(aes(y = children, color = "Below 18")) + geom_line(aes(y = adult, color = "18-59")) + geom_line(aes(y = elderly, color = "60 and above")) + scale_y_continuous(breaks = pretty_breaks(), labels = label_number(suffix = " M", scale = 1e-6)) + scale_x_date(date_breaks = "1 month", labels = date_format("%d-%b")) + labs(x = "Date", y = "Total Registration", title = "Cumulative Total Registration For Vaccination in Malaysia", color = "Age Class")
```

```{r}
# map ??
ggplot(reg_state, aes(as.Date(date))) + geom_line(aes(y = total, color = "Total")) + facet_wrap(~ state) + geom_density(alpha = 1) + scale_y_continuous(labels = label_number(suffix = " M", scale = 1e-6))
#+ scale_y_continuous(breaks = pretty_breaks(), labels = comma) 
#+ scale_x_date(date_breaks = "1 month", labels = date_format("%d-%b"))
```

```{r}
population_states <- population[-c(1),]
population_states <- subset(population_states, select = -c(idxs))
#population_states <- subset(population_states, select = -c(pop_12, pop_18, pop_60))

population_states <- population_states[order(population_states$state),]
#View(population_states)
pop_states <- population_states[-c(12, 14, 16),]
pop_kv <- population_states[c(12, 14, 16),]
pop_kv <- data.frame(state = "Klang Valley", pop = sum(pop_kv$pop))

r_state <- tail(reg_state, n = 16)
#View(r_state)

#population_states <- rbind(pop_states, pop_kv)

# Total By State
reg_rate <- round(r_state$total/population_states$pop * 100, digits = 2)
reg_rate <- data.frame(state = population_states$state, rate = reg_rate)
#View(reg_rate)

# Total Adult by State
reg_rate_adult <- round((r_state$total - r_state$children)/(population_states$pop_18 + population_states$pop_60) * 100, digits = 2)
reg_rate_adult <- data.frame(state = population_states$state, rate = reg_rate_adult)

reg_rate_children <- round(r_state$children/(population_states$pop -  population_states$pop_18 - population_states$pop_60) * 100, digits = 2)
reg_rate_children <- data.frame(state = population_states$state, rate = reg_rate_children)

ggplot(reg_rate, aes(x = state, y = rate, color = state)) + geom_bar(stat = "identity", fill = "white") + geom_text(aes(label = rate), hjust = 1.5 , size = 3.5) + labs(x = "State", y = "Percentage (%)", title = "Total Registered Percentage by State") + theme(legend.position = "none") + coord_flip()

ggplot(reg_rate_adult, aes(x = state, y = rate, color = state)) + geom_bar(stat = "identity", fill = "white") + geom_text(aes(label = rate), hjust = 1.5 , size = 3.5) + labs(x = "State", y = "Percentage (%)", title = "Total Adult Registered Percentage by State") + theme(legend.position = "none") + coord_flip()

ggplot(reg_rate_children, aes(x = state, y = rate, color = state)) + geom_bar(stat = "identity", fill = "white") + geom_text(aes(label = rate), hjust = 1.5 , size = 3.5) + labs(x = "State", y = "Percentage (%)", title = "Total Children Registered Percentage by State") + theme(legend.position = "none") + coord_flip()
```
